import { test,expect,type Page } from '@playwright/test';
import path from 'node:path';
const photo=path.resolve('public/photos/pothole.jpg');
const close=async(p:Page)=>{await p.getByRole('button',{name:'Close',exact:true}).click();};
const start=async(p:Page)=>{await p.goto('/');await expect(p.getByText('Saved in this browser',{exact:true})).toBeVisible();await expect(p.locator('.main-map .leaflet-marker-icon')).toHaveCount(11);};
const choose=async(p:Page,label:string,value:string)=>{await p.getByLabel(label,{exact:true}).selectOption(value);};

test('Gemini consent and successful live draft populate editable report fields',async({page})=>{
 await start(page);
 await page.getByRole('button',{name:'Report an issue',exact:true}).click();
 await page.getByRole('button',{name:/Use a labeled sample photo/}).click();
 await page.getByRole('button',{name:'Choose location',exact:true}).click();
 await page.getByRole('button',{name:'Place pin',exact:true}).click();
 await page.getByRole('button',{name:'Confirm this location',exact:true}).click();
 await page.getByRole('button',{name:'Review report',exact:true}).click();
 await choose(page,'AI mode','live');
 await expect(page.getByLabel('AI mode',{exact:true})).toContainText('Live AI · Google Gemini');
 const consent=page.getByRole('checkbox',{name:'I agree to send this photo and text to Google Gemini for this draft.'});
 await expect(consent).toBeVisible();
 await consent.check();
 await page.route('**/api/draft',async route=>{
  const input=route.request().postDataJSON();
  expect(input.consent).toBe(true);
  expect(input.image).toMatch(/^data:image\/jpeg;base64,/);
  expect(input).not.toHaveProperty('lat');
  expect(input).not.toHaveProperty('lng');
  await route.fulfill({json:{draft:{title:'Pothole beside the bus stop',category:'Pothole',description:'A damaged patch is visible in the road.',observations:'The road surface has a damaged patch.',residentFacts:'',questions:['When did you first notice it?'],suggestedTeam:'Roads'}}});
 });
 await page.getByRole('button',{name:'Help describe this issue',exact:true}).click();
 await expect(page.getByText('Live AI draft · check every field',{exact:true})).toBeVisible();
 await expect(page.getByLabel('Short title',{exact:true})).toHaveValue('Pothole beside the bus stop');
 await expect(page.getByRole('textbox',{name:'Factual description',exact:true})).toHaveValue('A damaged patch is visible in the road.');
 await page.getByLabel('Short title',{exact:true}).fill('Resident reviewed Gemini draft');
 await page.getByRole('button',{name:'Submit report',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Resident reviewed Gemini draft',exact:true})).toBeVisible();
});
test('map/card selection and reversible supports persist across reload and identities',async({page})=>{
 await start(page);await page.locator('.leaflet-marker-icon[title^="Open SF-001:"]').click();await expect(page.getByRole('heading',{name:'Pothole near the morning bus stop',exact:true})).toBeVisible();
 const support=page.getByRole('button',{name:/Support fixing this/});await support.click();await expect(page.getByRole('button',{name:/You support fixing this/})).toHaveText(/64/);await page.getByRole('button',{name:/You support fixing this/}).click();await expect(page.getByRole('button',{name:/Support fixing this/})).toHaveText(/63/);await support.click();await close(page);await choose(page,'Demo role','leo');await page.getByRole('button',{name:'Open report: Pothole near the morning bus stop',exact:true}).click();await expect(support).toHaveText(/64/);await support.click();await expect(page.getByRole('button',{name:/You support fixing this/})).toHaveText(/65/);await close(page);await expect(page.getByText('Saved in this browser',{exact:true})).toBeVisible();await page.reload();await expect(page.getByRole('button',{name:'Open report: Pothole near the morning bus stop',exact:true})).toContainText('65');
});
test('real uploaded photo, confirmed manual location, honest draft, staff workflow, completion and persistence',async({page})=>{
 await start(page);await page.getByRole('button',{name:'Report an issue',exact:true}).click();await page.getByLabel('Issue photo',{exact:true}).setInputFiles(photo);await expect(page.getByAltText('Your selected photo preview')).toBeVisible();await page.getByRole('button',{name:'Choose location',exact:true}).click();await page.getByLabel('Latitude',{exact:true}).fill('45.5169');await page.getByLabel('Longitude',{exact:true}).fill('-122.6510');await page.getByRole('button',{name:'Place pin',exact:true}).click();await page.getByRole('button',{name:'Confirm this location',exact:true}).click();await page.getByLabel('Location / nearby landmark',{exact:true}).fill('Demo crossing near Salmon');await page.getByLabel('What did you notice?',{exact:true}).fill('The road has an uneven patch beside the bus stop.');await page.getByRole('button',{name:'Review report',exact:true}).click();await choose(page,'Draft category','Pothole');await page.getByRole('button',{name:'Help describe this issue',exact:true}).click();await expect(page.getByText('Text-only draft · photo not analyzed',{exact:true})).toBeVisible();await expect(page.getByLabel('Visible observations',{exact:false})).toHaveValue('Photo not analyzed. Add only what you can see.');await page.getByLabel('Short title',{exact:true}).fill('Browser test street problem');await page.getByRole('button',{name:'Submit report',exact:true}).click();await expect(page.getByRole('heading',{name:'Browser test street problem',exact:true})).toBeVisible();await expect(page.locator('.report-sheet .badge').first()).toHaveText('Awaiting review');await expect(page.locator('.coordinates')).toContainText('45.516900, -122.651000');await close(page);
 await choose(page,'Demo role','staff');await page.getByRole('tab',{name:/Needs review/}).click();await page.getByRole('button',{name:'Open report: Browser test street problem',exact:true}).click();await choose(page,'Assigned team','Roads');await choose(page,'Staff priority','Urgent');await page.getByLabel('Priority reason',{exact:true}).fill('Inspection required beside the bus stop.');await choose(page,'Repair status','Planned');await page.getByLabel('Public progress note',{exact:true}).fill('Roads team assigned. Inspection planned for tomorrow.');await page.getByRole('button',{name:'Save public update',exact:true}).click();await expect(page.getByText('Roads team assigned. Inspection planned for tomorrow.',{exact:false}).first()).toBeVisible();await choose(page,'Repair status','In progress');await page.getByLabel('Public progress note',{exact:true}).fill('Crew is now repairing the road surface.');await page.getByRole('button',{name:'Save public update',exact:true}).click();await close(page);await choose(page,'Demo role','maya');await page.getByRole('button',{name:'Open report: Browser test street problem',exact:true}).click();await expect(page.getByText('Crew is now repairing the road surface.',{exact:false})).toBeVisible();await expect(page.locator('.report-sheet .badge').first()).toHaveText('In progress');await close(page);
 await choose(page,'Demo role','staff');await page.getByRole('button',{name:'Open report: Browser test street problem',exact:true}).click();await choose(page,'Repair status','Fixed');await page.getByLabel('Public completion update',{exact:true}).fill('Road patched and inspected.');await page.getByLabel('Completion photo',{exact:true}).setInputFiles(path.resolve('public/photos/repaired.jpg'));await page.getByRole('button',{name:'Save public update',exact:true}).click();await expect(page.locator('.after-photo img')).toBeVisible();await close(page);await expect(page.getByText('Saved in this browser',{exact:true})).toBeVisible();await page.reload();await page.getByRole('button',{name:'Open report: Browser test street problem',exact:true}).click();await expect(page.locator('.detail-cover img')).toHaveAttribute('src',/^data:image\/jpeg;base64,/);await expect(page.locator('.after-photo img')).toHaveAttribute('src',/^data:image\/jpeg;base64,/);await expect(page.getByText('Road patched and inspected.',{exact:false})).toBeVisible();await expect(page.locator('.timeline li')).toHaveCount(4);
});
test('category/status filtering, empty state, staff queue and seed completion history',async({page})=>{await start(page);await choose(page,'Category filter','Other');await choose(page,'Status filter','Fixed');await expect(page.getByRole('heading',{name:'No reports in this view',exact:true})).toBeVisible();await page.getByRole('button',{name:'Clear filters',exact:true}).click();await choose(page,'Sort reports','supported');await expect(page.locator('.issue-card').first()).toContainText('Pothole near the morning bus stop');await choose(page,'Demo role','staff');await page.getByRole('tab',{name:/Urgent/}).click();await expect(page.locator('.issue-card')).toHaveCount(2);await expect(page.locator('.issue-card').last()).toContainText('4');await page.getByRole('tab',{name:'All reports',exact:true}).click();await choose(page,'Status filter','Fixed');await page.locator('.issue-card').first().click();await expect(page.locator('.timeline li')).toHaveCount(5);await expect(page.locator('.after-photo')).toContainText('different scene');});
test('sample draft is labeled, live missing credentials and provider failure leave manual fields usable',async({page})=>{await start(page);await page.getByRole('button',{name:'Report an issue',exact:true}).click();await page.getByRole('button',{name:/Use a labeled sample photo/}).click();await page.getByRole('button',{name:'Choose location',exact:true}).click();await page.getByRole('button',{name:'Place pin',exact:true}).click();await page.getByRole('button',{name:'Confirm this location',exact:true}).click();await page.getByRole('button',{name:'Review report',exact:true}).click();await page.getByRole('button',{name:'Help describe this issue',exact:true}).click();await expect(page.getByText('Sample AI draft · curated example',{exact:true})).toBeVisible();await choose(page,'AI mode','live');await page.getByRole('button',{name:'Help describe this issue',exact:true}).click();await expect(page.getByRole('alert')).toContainText('Confirm you want to send');await page.route('**/api/draft',route=>route.fulfill({status:503,json:{error:'Live AI is not configured. Set GEMINI_API_KEY on the server.'}}));await page.getByRole('checkbox').check();await page.getByRole('button',{name:'Retry: Help describe this issue',exact:true}).click();await expect(page.getByRole('alert')).toContainText('Live AI is not configured');await page.route('**/api/draft',route=>route.fulfill({status:502,json:{error:'Gemini billing credits are unavailable. Check billing in Google AI Studio, then retry.'}}));await page.getByRole('button',{name:'Retry: Help describe this issue',exact:true}).click();await expect(page.getByRole('alert')).toContainText('Gemini billing credits are unavailable');await expect(page.getByRole('alert')).toContainText('You can still edit and submit manually');await page.getByLabel('Short title',{exact:true}).fill('Manual after AI failure');await page.getByRole('button',{name:'Submit report',exact:true}).click();await expect(page.getByRole('heading',{name:'Manual after AI failure',exact:true})).toBeVisible();});
test('invalid upload and map tile failure have usable fallbacks',async({page})=>{await page.route('**/tile.openstreetmap.org/**',route=>route.abort());await start(page);await expect(page.getByText('Map tiles unavailable',{exact:true})).toBeVisible();await expect(page.locator('.leaflet-marker-icon')).toHaveCount(11);await page.getByRole('button',{name:'Report an issue',exact:true}).click();await page.getByLabel('Issue photo',{exact:true}).setInputFiles({name:'bad.svg',mimeType:'image/svg+xml',buffer:Buffer.from('<svg/>')});await expect(page.getByRole('alert')).toContainText('Choose a JPEG, PNG, or WebP');await page.getByLabel('Issue photo',{exact:true}).setInputFiles({name:'corrupt.jpg',mimeType:'image/jpeg',buffer:Buffer.from('not a picture')});await expect(page.getByRole('alert')).toContainText('could not be opened');await page.getByLabel('Issue photo',{exact:true}).setInputFiles(photo);await page.getByRole('button',{name:'Choose location',exact:true}).click();await page.getByRole('button',{name:'Place pin',exact:true}).click();await page.getByRole('button',{name:'Confirm this location',exact:true}).click();await expect(page.getByRole('button',{name:'Review report',exact:true})).toBeEnabled();});
test('unavailable IndexedDB warns and leaves session workflow usable',async({page})=>{await page.addInitScript(()=>Object.defineProperty(window,'indexedDB',{get(){throw new Error('Unavailable');}}));await page.goto('/');await expect(page.getByText('Browser storage is unavailable.',{exact:false})).toBeVisible();await page.getByRole('button',{name:'Open report: Pothole near the morning bus stop',exact:true}).click();await page.getByRole('button',{name:/Support fixing this/}).click();await expect(page.getByRole('button',{name:/You support fixing this/})).toHaveText(/64/);});
test('mobile map/list/detail and reporting are usable without horizontal overflow',async({page})=>{await page.setViewportSize({width:390,height:844});await start(page);await expect(page.getByRole('tab',{name:'Map',exact:true})).toBeVisible();await page.getByRole('tab',{name:/List ·/}).click();await expect(page.locator('.issue-card').first()).toBeVisible();await page.locator('.issue-card').first().click();await expect(page.locator('.report-sheet')).toBeVisible();await page.getByRole('button',{name:/Support fixing this/}).click();await close(page);await page.getByRole('button',{name:'Report an issue',exact:true}).click();await page.getByLabel('Issue photo',{exact:true}).setInputFiles(photo);await page.getByRole('button',{name:'Choose location',exact:true}).click();await page.getByRole('button',{name:'Place pin',exact:true}).click();await page.getByRole('button',{name:'Confirm this location',exact:true}).click();await expect(page.getByRole('button',{name:'Review report',exact:true})).toBeEnabled();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.getByRole('button',{name:'Review report',exact:true}).click();await page.getByLabel('Short title',{exact:true}).fill('Mobile street report');await page.getByLabel('Factual description',{exact:true}).fill('A road defect noticed on a walk.');await choose(page,'Draft category','Pothole');await page.getByRole('button',{name:'Submit report',exact:true}).click();await expect(page.getByRole('heading',{name:'Mobile street report',exact:true})).toBeVisible();await close(page);await choose(page,'Demo role','staff');await page.getByRole('button',{name:'Open report: Mobile street report',exact:true}).click();await choose(page,'Assigned team','Roads');await choose(page,'Repair status','Planned');await page.getByLabel('Public progress note',{exact:true}).fill('Mobile staff update published.');await page.getByRole('button',{name:'Save public update',exact:true}).click();await close(page);await choose(page,'Demo role','maya');await page.getByRole('button',{name:'Open report: Mobile street report',exact:true}).click();await expect(page.getByText('Mobile staff update published.',{exact:false})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);});
test('reset removes new reports and support changes together',async({page})=>{await start(page);await page.getByRole('button',{name:'Open report: Pothole near the morning bus stop',exact:true}).click();await page.getByRole('button',{name:/Support fixing this/}).click();await close(page);await page.getByRole('button',{name:'Reset demo',exact:true}).click();await page.getByRole('button',{name:'Reset demo',exact:true}).last().click();await expect(page.getByText('Saved in this browser',{exact:true})).toBeVisible();await page.reload();await expect(page.locator('.issue-card')).toHaveCount(11);await expect(page.locator('.issue-card').first()).toContainText('63');await page.screenshot({path:'outputs/streetfix-desktop.png',fullPage:true});});
