import test from 'node:test';
import assert from 'node:assert/strict';
import 'fake-indexeddb/auto';
import { applyStaff,filterReports,hasSupport,localDraft,seedSnapshot,snapshotSchema,supportCount,toggleSupport,type StaffPatch } from '../lib/streetfix';
import { readSnapshot,writeSnapshot } from '../lib/storage';
function patch(s=seedSnapshot(),id='SF-005'):StaffPatch{const r=s.reports.find(r=>r.id===id)!;return {title:r.title,description:r.description,category:r.category,priority:r.priority,priorityReason:r.priorityReason,team:r.team,status:r.status,targetDate:r.targetDate,note:'Staff inspection arranged.',reviewAction:'confirm'};}
test('seed data separates popularity, urgency, review, and completed history',()=>{const s=snapshotSchema.parse(seedSnapshot());assert.equal(s.reports.length,11);assert.equal(s.reports.find(r=>r.id==='SF-001')!.priority,'Normal');assert.equal(supportCount(s,'SF-001'),63);assert.equal(s.reports.find(r=>r.id==='SF-002')!.priority,'Urgent');assert.equal(supportCount(s,'SF-002'),4);const fixed=s.reports.find(r=>r.status==='Fixed')!;assert.deepEqual(fixed.timeline.filter(e=>e.status).map(e=>e.status),['Reported','Reported','Planned','In progress','Fixed']);assert.ok(fixed.photos.some(p=>p.kind==='after'));});
test('support is a reversible relationship for a stable identity',()=>{let s=seedSnapshot();s=toggleSupport(s,'SF-001','demo-maya');assert.equal(supportCount(s,'SF-001'),64);assert.equal(hasSupport(s,'SF-001','demo-maya'),true);s=toggleSupport(s,'SF-001','demo-maya');assert.equal(supportCount(s,'SF-001'),63);s=toggleSupport(s,'SF-001','demo-leo');s=toggleSupport(s,'SF-001','demo-maya');assert.equal(supportCount(s,'SF-001'),65);assert.equal(supportCount({...s,supports:[...s.supports,s.supports[0]]},'SF-001'),65);});
test('staff confirm and assign without changing supports; updates retain history',()=>{const s=seedSnapshot(),next=applyStaff(s,'SF-005',{...patch(s),status:'Planned',priority:'Urgent',priorityReason:'Staff inspection established an access obstruction.',team:'Signs & Signals'});const r=next.reports.find(r=>r.id==='SF-005')!;assert.equal(r.review,'confirmed');assert.equal(r.status,'Planned');assert.equal(r.priority,'Urgent');assert.equal(r.timeline.length,2);assert.deepEqual(next.supports,s.supports);assert.equal(r.photos[0].src,s.reports[4].photos[0].src);});
test('invalid review and skipped/backward transitions are rejected',()=>{const s=seedSnapshot();assert.throws(()=>applyStaff(s,'SF-005',{...patch(s),reviewAction:'keep',status:'Planned'}),/Confirm/);assert.throws(()=>applyStaff(s,'SF-005',{...patch(s),status:'Fixed'}),/one at a time/);assert.throws(()=>applyStaff(s,'SF-003',{...patch(s,'SF-003'),status:'Reported'}),/one at a time/);assert.throws(()=>applyStaff(s,'SF-005',{...patch(s),priorityReason:''}),/Explain/);});
test('fixed reports retain support, original photos, and append completion data',()=>{const s=seedSnapshot(),id='SF-003';assert.throws(()=>applyStaff(s,id,{...patch(s,id),status:'Fixed',note:''}),/completion update/);const next=applyStaff(s,id,{...patch(s,id),status:'Fixed',note:'Column replaced and checked.',completionPhoto:{id:'after',src:'data:image/jpeg;base64,ZmFrZQ==',kind:'after',alt:'Completed work'}});const r=next.reports.find(r=>r.id===id)!;assert.equal(r.photos.length,2);assert.equal(r.timeline.at(-1)!.status,'Fixed');assert.equal(supportCount(next,id),supportCount(s,id));assert.deepEqual(r.timeline.slice(0,-1),s.reports.find(r=>r.id===id)!.timeline);});
test('duplicate keeps its history and supports without inflating canonical count',()=>{const s=seedSnapshot(),next=applyStaff(s,'SF-005',{...patch(s),reviewAction:'duplicate',canonicalId:'SF-009'});assert.equal(next.reports.find(r=>r.id==='SF-005')!.canonicalId,'SF-009');assert.equal(supportCount(next,'SF-009'),9);assert.equal(supportCount(next,'SF-005'),17);assert.deepEqual(toggleSupport(next,'SF-005','demo-maya'),next);assert.throws(()=>applyStaff(s,'SF-005',{...patch(s),reviewAction:'duplicate',canonicalId:'SF-005'}),/canonical/);});
test('filters and transparent queue sorts produce correct results and empty state',()=>{const s=seedSnapshot();assert.equal(filterReports(s,'all','awaiting','all','newest').length,3);assert.equal(filterReports(s,'Other','Fixed','all','newest').length,0);assert.equal(filterReports(s,'all','all','supported','newest')[0].id,'SF-001');assert.ok(filterReports(s,'all','all','urgent','newest').every(r=>r.priority==='Urgent'&&r.status!=='Fixed'));assert.equal(filterReports(s,'all','all','all','newest')[0].id,'SF-001');});
test('arbitrary upload sample mode uses only supplied text and manual category',()=>{const d=localDraft('There is something beside the ramp.','Sidewalk / accessibility','My report');assert.equal(d.description,'There is something beside the ramp.');assert.equal(d.observations,'Photo not analyzed. Add only what you can see.');assert.equal(d.suggestedTeam,'Sidewalks');assert.ok(d.questions.some(q=>q.includes('wheelchair')));});
test('existing support can be withdrawn after duplicate review; new supports are blocked',()=>{let s=toggleSupport(seedSnapshot(),'SF-005','demo-maya');s=applyStaff(s,'SF-005',{...patch(s),reviewAction:'duplicate',canonicalId:'SF-009'});assert.equal(supportCount(s,'SF-005'),18);assert.equal(supportCount(s,'SF-009'),9);s=toggleSupport(s,'SF-005','demo-maya');assert.equal(supportCount(s,'SF-005'),17);assert.equal(hasSupport(s,'SF-005','demo-maya'),false);assert.deepEqual(toggleSupport(s,'SF-005','demo-maya'),s);});
test('staff oldest-first queues override a resident support sort',()=>{const s=seedSnapshot();const urgent=filterReports(s,'all','all','urgent','supported');assert.equal(urgent[0].id,'SF-011');assert.equal(urgent[1].id,'SF-002');const review=filterReports(s,'all','all','review','supported');assert.equal(review[0].id,'SF-010');assert.equal(review.at(-1)!.id,'SF-005');});
test('IndexedDB persists photos, support relationships, and staff updates; reset is atomic',async()=>{let s=seedSnapshot();s=toggleSupport(s,'SF-001','demo-maya');s=applyStaff(s,'SF-005',patch(s));s.reports[0].photos.push({id:'uploaded',src:'data:image/jpeg;base64,ZmFrZQ==',alt:'Test photo',kind:'before'});await writeSnapshot(s);assert.deepEqual(await readSnapshot(),s);const reset=seedSnapshot();await writeSnapshot(reset);assert.deepEqual(await readSnapshot(),reset);});
