import { chromium } from '@playwright/test';
import { mkdirSync,writeFileSync } from 'node:fs';
mkdirSync('outputs',{recursive:true});
const browser=await chromium.launch({channel:'msedge',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:5173');
await page.getByText('Saved in this browser',{exact:true}).waitFor();
await page.locator('.leaflet-marker-icon').nth(10).waitFor();
await page.waitForTimeout(1200);
await page.screenshot({path:'outputs/streetfix-desktop.png',fullPage:true});
await page.getByLabel('Demo role',{exact:true}).selectOption('staff');
await page.getByRole('tab',{name:/Urgent/}).click();
await page.waitForTimeout(600);
await page.screenshot({path:'outputs/streetfix-staff.png',fullPage:true});
await page.getByLabel('Demo role',{exact:true}).selectOption('maya');
await page.getByRole('button',{name:'Open report: Pothole near the morning bus stop',exact:true}).click();
await page.locator('.report-sheet h2').waitFor();
await page.waitForTimeout(600);
await page.screenshot({path:'outputs/streetfix-detail.png'});
await page.getByRole('button',{name:'Close',exact:true}).click();
await page.setViewportSize({width:390,height:844});
await page.getByRole('tab',{name:'Map',exact:true}).click();
await page.waitForTimeout(500);
await page.screenshot({path:'outputs/streetfix-mobile.png'});
const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);
const tileCount=await page.locator('.leaflet-tile-loaded').count();
const webMcpAvailable=await page.evaluate(()=>typeof document.modelContext?.registerTool==='function');
const summary={pageErrors:errors,mobileHorizontalOverflow:overflow,loadedTiles:tileCount,webMcpAvailable};
writeFileSync('outputs/browser-inspection.json',JSON.stringify(summary,null,2));
console.log(JSON.stringify(summary));
await browser.close();
if(errors.length||overflow)process.exitCode=1;
