'use client';
import { useCallback,useEffect,useRef,useState } from 'react';
import { MapPin,Plus,Users,Check,Camera,Building2,Map as MapIcon,List,SlidersHorizontal,Clock,ArrowUpRight,RotateCcw,Sparkles,Upload,LoaderCircle,ShieldCheck,TriangleAlert,Navigation,Image as ImageIcon,Heart } from 'lucide-react';
import { Dialog,DialogContent,DialogTitle,DialogDescription } from '@/components/ui/dialog';
import { Sheet,SheetContent,SheetTitle,SheetDescription } from '@/components/ui/sheet';
import { AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogAction,AlertDialogCancel,AlertDialogFooter } from '@/components/ui/alert-dialog';
import { NativeSelect } from '@/components/ui/native-select';
import { Tabs,TabsList,TabsTrigger } from '@/components/ui/tabs';
import { Checkbox } from '@/components/ui/checkbox';
import { Toaster } from '@/components/ui/sonner';
import { toast } from 'sonner';
import { StreetMap } from './street-map';
import { applyStaff,categories,center,draftSchema,filterReports,hasSupport,localDraft,priorities,routing,seedSnapshot,statuses,supportCount,teams,toggleSupport,type Category,type Draft,type Photo,type Report,type Snapshot,type StaffPatch } from '@/lib/streetfix';
import { readPhoto,readSnapshot,writeSnapshot } from '@/lib/storage';

const date=(value:string)=>new Date(value).toLocaleDateString('en-US',{month:'short',day:'numeric',timeZone:'America/New_York'});
function Choose({label,value,options,onChange,disabled=false}:{label:string;value:string;options:readonly (string|{value:string;label:string})[];onChange:(v:string)=>void;disabled?:boolean}){
 return <NativeSelect aria-label={label} value={value} disabled={disabled} onChange={e=>onChange(e.target.value)}>{options.map(v=>typeof v==='string'?<option key={v} value={v}>{v}</option>:<option key={v.value} value={v.value}>{v.label}</option>)}</NativeSelect>;
}
function Badge({report}:{report:Report}){const label=report.review==='awaiting'?'Awaiting review':report.review==='duplicate'?'Duplicate':report.status;return <span className={`badge ${label.toLowerCase().replaceAll(' ','-')}`}><i/>{label}</span>;}
function IssueImage({photo,className}:{photo:Photo;className?:string}){const [error,setError]=useState(false);return error?<div className={`image-error ${className||''}`}><ImageIcon/><span>Photo unavailable</span></div>:<img className={className} src={photo.src} alt={photo.alt} onError={()=>setError(true)}/>;}

export default function StreetFix(){
 const [data,setData]=useState<Snapshot>(()=>seedSnapshot()),[loaded,setLoaded]=useState(false),[storage,setStorage]=useState<'loading'|'saved'|'saving'|'session'>('loading');
 const latest=useRef(data),writes=useRef(Promise.resolve()),saveGeneration=useRef(0);latest.current=data;
 const [role,setRole]=useState('maya'),[category,setCategory]=useState('all'),[status,setStatus]=useState('all'),[sort,setSort]=useState('newest'),[queue,setQueue]=useState('all'),[mobileView,setMobileView]=useState('map');
 const [selected,setSelected]=useState<string|null>(null),[detailOpen,setDetailOpen]=useState(false),[reportOpen,setReportOpen]=useState(false),[resetOpen,setResetOpen]=useState(false);
 const staff=role==='staff',resident=role==='leo'?'demo-leo':'demo-maya';
 const persist=useCallback((next:Snapshot)=>{const generation=++saveGeneration.current;setStorage('saving');writes.current=writes.current.catch(()=>{}).then(()=>writeSnapshot(next)).then(()=>{if(generation===saveGeneration.current)setStorage('saved');}).catch(()=>{if(generation===saveGeneration.current)setStorage('session');});},[]);
 const commit=useCallback((change:(current:Snapshot)=>Snapshot)=>{const next=change(latest.current);latest.current=next;setData(next);persist(next);},[persist]);
 useEffect(()=>{let cancelled=false;readSnapshot().then(saved=>{if(cancelled)return;const next=saved||seedSnapshot();latest.current=next;setData(next);setLoaded(true);if(!saved)persist(next);else setStorage('saved');}).catch(()=>{if(!cancelled){setStorage('session');setLoaded(true);}});return()=>{cancelled=true;};},[persist]);
 const visible=filterReports(data,category,status,staff?queue:'all',sort),selectedReport=data.reports.find(r=>r.id===selected);
 const select=(id:string)=>{setSelected(id);setDetailOpen(true);};
 const changeRole=(value:string)=>{setRole(value);setQueue('all');};
 const clearFilters=()=>{setCategory('all');setStatus('all');setQueue('all');};
 useEffect(()=>{
  const registry=(document as unknown as {modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>Promise<void>|void}}).modelContext;if(!registry?.registerTool)return;const lifecycle=new AbortController();
  Promise.resolve(registry.registerTool({name:'browse_streetfix_reports',title:'Browse StreetFix reports',description:'Read reports and support counts in this local demo. Does not change reports.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:(input:unknown)=>{if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).length)throw new Error('Expected an empty object.');return latest.current.reports.map(r=>({id:r.id,title:r.title,status:r.status,review:r.review,support:supportCount(latest.current,r.id)}));}},{signal:lifecycle.signal})).catch(()=>{});
  Promise.resolve(registry.registerTool({name:'open_streetfix_report',title:'Open report',description:'Open a report in the visible detail sheet; does not edit or support it.',inputSchema:{type:'object',properties:{id:{type:'string'}},required:['id'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:async(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).some(k=>k!=='id'))throw new Error('Expected only a report ID.');const id=(input as {id?:string}).id;if(typeof id!=='string'||!latest.current.reports.some(r=>r.id===id))throw new Error('Report not found.');setSelected(id);setDetailOpen(true);await new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve())));return {opened:id};}},{signal:lifecycle.signal})).catch(()=>{});
  return()=>lifecycle.abort();
 },[]);
 return <main className="streetfix">
  <header className="site-header"><a className="brand" href="/" aria-label="StreetFix home"><span className="brand-mark"><MapPin size={24}/><Check size={10}/></span>StreetFix<span className="brand-dot">.</span></a><div className="header-nav"><MapIcon size={17}/> Neighborhood</div><div className="header-actions"><span className="demo-label">DEMO ROLE</span><Choose label="Demo role" value={role} options={[{value:'maya',label:'Resident · Maya'},{value:'leo',label:'Resident · Leo'},{value:'staff',label:'City staff'}]} onChange={changeRole}/><span className="avatar">{staff?<Building2 size={18}/>:role==='leo'?'L':'M'}</span></div></header>
  <section className="intro"><div><div className="eyebrow"><span/> OUR SHARED STREETS</div><h1>{staff?'A clearer view. A connected repair.':'A better neighborhood starts here.'}</h1><p>{staff?'Review reports, set priorities, and keep the neighborhood in the loop.':'Photograph a street problem, get your neighbors behind it, and follow its repair on one shared map.'}</p></div><button className="primary report-cta" onClick={()=>setReportOpen(true)} disabled={!loaded}><Plus size={19}/> Report an issue</button></section>
  {storage==='session'&&<div className="storage-notice" role="status"><TriangleAlert size={17}/><span>Browser storage is unavailable. Changes work in this session but may be lost on reload.</span><button onClick={()=>persist(latest.current)}>Retry saving</button></div>}
  <section className="workspace-controls"><div className="view-tabs">{staff?<Tabs value={queue} onValueChange={setQueue}><TabsList className="queue-tabs"><TabsTrigger value="all">All reports</TabsTrigger><TabsTrigger value="review">Needs review <span>{data.reports.filter(r=>r.review==='awaiting').length}</span></TabsTrigger><TabsTrigger value="urgent">Urgent <span>{data.reports.filter(r=>r.priority==='Urgent'&&r.status!=='Fixed'&&r.review!=='duplicate').length}</span></TabsTrigger><TabsTrigger value="supported">Most supported</TabsTrigger><TabsTrigger value="progress">In progress</TabsTrigger></TabsList></Tabs>:<div className="neighborhood-label"><MapPin size={17}/><strong>Harborview neighborhood</strong><span>{data.reports.length} reports</span></div>}</div><div className="filter-controls"><SlidersHorizontal size={16}/><Choose label="Category filter" value={category} options={[{value:'all',label:'All categories'},...categories]} onChange={setCategory}/><Choose label="Status filter" value={status} options={[{value:'all',label:'All statuses'},{value:'awaiting',label:'Awaiting review'},...statuses]} onChange={setStatus}/></div></section>
  <div className="mobile-switch"><Tabs value={mobileView} onValueChange={setMobileView}><TabsList><TabsTrigger value="map"><MapIcon size={16}/> Map</TabsTrigger><TabsTrigger value="list"><List size={16}/> List · {visible.length}</TabsTrigger></TabsList></Tabs></div>
  <section className={`workspace mobile-${mobileView}`} aria-label="Neighborhood reports"><div className="main-map"><StreetMap reports={visible} selected={selected} onSelect={select}/><div className="map-caption"><ShieldCheck size={15}/> Fictional reports on a real base map. Photo locations are illustrative.</div></div>
   <aside className="issue-panel"><div className="list-heading"><div><h2>{staff?queue==='review'?'Needs a first look':queue==='urgent'?'Staff urgency':queue==='supported'?'Community support':queue==='progress'?'Work underway':'Work queue':'Around the neighborhood'}</h2><span>{visible.length} {visible.length===1?'report':'reports'}{staff&&(queue==='urgent'||queue==='review')?' · oldest first':''}</span></div><Choose label="Sort reports" value={staff&&queue==='supported'?'supported':staff&&(queue==='urgent'||queue==='review')?'oldest':sort} options={[{value:'newest',label:'Newest'},{value:'supported',label:'Most supported'},{value:'oldest',label:'Oldest'}]} onChange={v=>{setSort(v);if(queue==='urgent'||queue==='review'||queue==='supported')setQueue('all');}}/></div>
    {staff&&<p className="queue-note">Staff priority and community support are separate. {queue==='supported'?'Support count, then oldest first.':queue==='urgent'||queue==='review'?'Oldest first in this view.':'Use the sort control to order reports.'}</p>}
    <div className="issue-list">{visible.map(r=><button key={r.id} className={`issue-card ${selected===r.id?'active':''}`} onClick={()=>select(r.id)} aria-label={`Open report: ${r.title}`}><div className="card-photo"><IssueImage photo={r.photos[0]}/><Badge report={r}/><span className="category-icon">{r.category==='Sidewalk / accessibility'?<Navigation size={17}/>:r.category==='Broken streetlight'?<Sparkles size={17}/>:<MapPin size={17}/>}</span></div><div className="card-body"><span className="card-category">{r.category}</span><h3>{r.title}</h3><p><MapPin size={13}/>{r.location}</p>{staff&&<div className="staff-card-info"><span className={r.priority==='Urgent'?'urgent-label':''}>{r.priority} priority</span><span>{Math.max(0,Math.floor((Date.now()-Date.parse(r.submittedAt))/86400000))} days old</span>{r.accessConcern&&<span className="access-label">Reported access concern</span>}</div>}<div className="card-bottom"><span><Users size={15}/><strong>{supportCount(data,r.id)}</strong> support{hasSupport(data,r.id,resident)&&!staff&&<Check size={13}/>}</span><span>{date(r.submittedAt)}<ArrowUpRight size={15}/></span></div></div></button>)}
     {!visible.length&&<div className="empty-state"><MapPin size={28}/><h3>No reports in this view</h3><p>Try another category or status to see what’s nearby.</p><button className="secondary" onClick={clearFilters}>Clear filters</button></div>}
    </div><div className="panel-foot"><span><Heart size={14}/> Small actions. Shared progress.</span></div>
   </aside>
  </section>
  <footer className="site-footer"><span>StreetFix · Fictional interview prototype</span><div><span role="status">{storage==='saved'?'Saved in this browser':storage==='saving'?'Saving…':storage==='loading'?'Loading local records…':'Session only'}</span><a href="/IMAGE-PROVENANCE.md" target="_blank" rel="noreferrer">Photo credits</a><button onClick={()=>setResetOpen(true)}><RotateCcw size={13}/> Reset demo</button></div></footer>
  <Sheet open={detailOpen} onOpenChange={setDetailOpen}><SheetContent className="report-sheet" aria-describedby="report-detail-description"><SheetDescription id="report-detail-description" className="sr-only">Issue photos, resident context, community support, and public repair updates.</SheetDescription>{selectedReport&&<ReportDetail key={selectedReport.id} report={selectedReport} data={data} staff={staff} resident={resident} commit={commit} select={select}/>}</SheetContent></Sheet>
  <Dialog open={reportOpen} onOpenChange={setReportOpen}><DialogContent className="report-dialog"><DialogTitle>Make your street a little better.</DialogTitle><DialogDescription>A photo, a place, and what you noticed. You review every detail.</DialogDescription>{reportOpen&&<ReportForm onSubmit={report=>{commit(s=>({...s,reports:[report,...s.reports]}));clearFilters();setSort('newest');setReportOpen(false);select(report.id);toast.success('Report submitted · awaiting staff review');}}/>}</DialogContent></Dialog>
  <AlertDialog open={resetOpen} onOpenChange={setResetOpen}><AlertDialogContent><AlertDialogTitle>Reset the local demo?</AlertDialogTitle><AlertDialogDescription>This removes submitted reports, uploaded photos, staff updates, and demo supports from this browser and restores the original 11 reports.</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel>Keep my changes</AlertDialogCancel><AlertDialogAction onClick={()=>{commit(()=>seedSnapshot());setSelected(null);setDetailOpen(false);clearFilters();toast.success('Demo restored');}}>Reset demo</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  <Toaster position="bottom-center"/>
 </main>;
}

function ReportDetail({report:r,data,staff,resident,commit,select}:{report:Report;data:Snapshot;staff:boolean;resident:string;commit:(change:(s:Snapshot)=>Snapshot)=>void;select:(id:string)=>void}){
 const supported=hasSupport(data,r.id,resident),canonical=data.reports.find(v=>v.id===r.canonicalId);
 return <div className="detail-inner"><div className="detail-cover"><IssueImage photo={r.photos[0]}/><Badge report={r}/></div><div className="detail-content"><div className="detail-meta"><span>{r.id} · {r.category}</span><span>{date(r.submittedAt)}</span></div><SheetTitle>{r.title}</SheetTitle><p className="detail-location"><MapPin size={17}/>{r.location}</p><p className="photo-caption">{r.photos[0].provenance||'Resident-uploaded photo'}</p>
  {canonical&&<div className="duplicate-notice"><strong>This is a duplicate report</strong><p>Its history and supports are preserved here. Supports were not added to the canonical report.</p><button onClick={()=>select(canonical.id)}>Open {canonical.id}: {canonical.title}</button></div>}
  {!staff&&(r.review!=='duplicate'||supported)&&<button className={`support-button ${supported?'supported':''}`} aria-pressed={supported} onClick={()=>commit(s=>toggleSupport(s,r.id,resident))}>{supported?<Check size={18}/>:<Users size={18}/>}<span>{r.review==='duplicate'?'Withdraw my support':supported?'You support fixing this':'Support fixing this'}</span><strong>{supportCount(data,r.id)}</strong></button>}
  {staff&&<div className="community-count"><Users size={18}/><strong>{supportCount(data,r.id)} supports</strong><span>Community support · separate from staff priority</span></div>}
  <section className="detail-section"><h3>The report</h3><p>{r.description}</p><div className="context-box"><span>RESIDENT-REPORTED CONTEXT</span><p>{r.residentContext||'No additional context supplied.'}</p>{r.accessConcern&&<p className="access-label"><Navigation size={14}/>{r.accessConcern}</p>}</div><details><summary>Image observations</summary><p>{r.observations||'No image analysis or observations supplied.'}</p></details></section>
  <section className="detail-section"><h3>Precise location</h3><StreetMap reports={[]} pin={[r.lat,r.lng]} compact/><p className="coordinates">Confirmed pin · {r.lat.toFixed(6)}, {r.lng.toFixed(6)}</p></section>
  <section className="detail-section"><div className="section-heading"><h3>Repair progress</h3><Badge report={r}/></div><ol className="repair-stages">{statuses.map((status,i)=><li key={status} className={statuses.indexOf(r.status)>=i?'complete':''}><span>{statuses.indexOf(r.status)>i?<Check size={12}/>:i+1}</span>{status}</li>)}</ol><dl className="repair-info"><div><dt>Staff priority</dt><dd className={r.priority==='Urgent'?'urgent-label':''}>{r.priority}</dd></div><div><dt>Assigned team</dt><dd>{r.team}</dd></div>{r.targetDate&&<div><dt>Target date</dt><dd>{date(r.targetDate+'T12:00:00-04:00')} · estimate</dd></div>}</dl><p className="priority-reason">{r.priorityReason}</p>
   {r.photos.filter(p=>p.kind==='after').map(p=><figure className="after-photo" key={p.id}><IssueImage photo={p}/><figcaption><Check size={14}/> Completion photo · {p.provenance||'Uploaded by city staff'}</figcaption></figure>)}
   <h4>Public updates & history</h4><ol className="timeline">{[...r.timeline].reverse().map(e=><li key={e.id}><span className="timeline-dot"/><div><span className="timeline-meta">{e.actor} · {date(e.at)}{e.status?` · ${e.status}`:''}</span><p>{e.text}</p></div></li>)}</ol>
  </section>
  {staff&&r.review!=='duplicate'&&<StaffForm key={`${r.id}-${r.timeline.length}`} report={r} reports={data.reports} onSave={patch=>{try{commit(s=>applyStaff(s,r.id,patch));toast.success('Report updated · visible to residents');return true;}catch(e){toast.error((e as Error).message);return false;}}}/>}
 </div></div>;
}

function PhotoPicker({src,onPhoto,onRemove,label='Issue photo'}:{src:string;onPhoto:(src:string)=>void;onRemove:()=>void;label?:string}){
 const input=useRef<HTMLInputElement>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const upload=async(file?:File)=>{if(!file)return;setError('');setBusy(true);try{onPhoto(await readPhoto(file));}catch(e){setError((e as Error).message);}finally{setBusy(false);if(input.current)input.current.value='';}};
 return <div className="photo-picker"><input ref={input} type="file" aria-label={label} accept="image/jpeg,image/png,image/webp" onChange={e=>void upload(e.target.files?.[0])} className="sr-only"/>{src?<div className="upload-preview"><img src={src} alt="Your selected photo preview"/><div><button type="button" onClick={()=>input.current?.click()} disabled={busy}>Replace photo</button><button type="button" onClick={onRemove}>Remove</button></div></div>:<button type="button" className="upload-zone" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();void upload(e.dataTransfer.files[0]);}} onClick={()=>input.current?.click()} disabled={busy}>{busy?<LoaderCircle className="spin" size={30}/>:<Upload size={30}/>}<strong>{busy?'Preparing your photo…':'Choose a photo or drop it here'}</strong><span>JPEG, PNG, WebP · up to 5 MB</span></button>}{busy&&src&&<p role="status">Preparing your photo…</p>}{error&&<p className="form-error" role="alert">{error}</p>}</div>;
}

function ReportForm({onSubmit}:{onSubmit:(r:Report)=>void}){
 const [step,setStep]=useState(1),[photo,setPhoto]=useState(''),[sample,setSample]=useState(false),[pin,setPin]=useState<[number,number]|null>(null),[confirmed,setConfirmed]=useState(false),[lat,setLat]=useState(String(center[0])),[lng,setLng]=useState(String(center[1])),[location,setLocation]=useState(''),[context,setContext]=useState(''),[access,setAccess]=useState('');
 const [title,setTitle]=useState(''),[category,setCategory]=useState<Category>('Other'),[description,setDescription]=useState(''),[observations,setObservations]=useState(''),[residentFacts,setResidentFacts]=useState(''),[draft,setDraft]=useState<Draft|null>(null),[mode,setMode]=useState('sample'),[consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[locating,setLocating]=useState(false);
 const updatePin=(p:[number,number])=>{setPin(p);setLat(String(p[0]));setLng(String(p[1]));setConfirmed(false);};
 const changePhoto=(src:string)=>{setPhoto(src);setSample(false);setDraft(null);setObservations('');setTitle('');setDescription('');setResidentFacts('');setCategory('Other');if(sample)setContext('');};
 const useSample=()=>{setPhoto('/photos/sidewalk.jpg');setSample(true);setTitle('Sidewalk obstruction beside the crossing');setCategory('Sidewalk / accessibility');setContext('I noticed an obstruction on my walk. I have not checked whether a wheelchair can pass.');setDescription('');setObservations('');setDraft(null);};
 const help=async()=>{setBusy(true);setError('');try{let result:Draft;if(mode==='live'){
   if(!consent)throw new Error('Confirm you want to send this photo and text to Google Gemini, then select Help describe this issue.');
   const image=photo.startsWith('data:')?photo:await fetch(photo).then(r=>r.blob()).then(blob=>new Promise<string>(resolve=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.readAsDataURL(blob);}));
   const response=await fetch('/api/draft',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({image,context,category,title,consent:true}),signal:AbortSignal.timeout(45000)});const body=await response.json() as {error?:string;draft?:unknown};if(!response.ok)throw new Error(body.error||'AI assistance is unavailable.');result=draftSchema.parse(body.draft);
  }else{await new Promise(resolve=>setTimeout(resolve,600));result=sample?{title:'Sidewalk obstruction beside the crossing',category:'Sidewalk / accessibility',description:'A barrier and equipment occupy part of a sidewalk. Please inspect the walking route.',observations:'Curated sample observation: a barrier and equipment are visible beside the walking path. The available passage width cannot be established from this photo.',residentFacts:context,questions:['Is there room for a wheelchair to pass?','Is there another accessible route?'],suggestedTeam:'Sidewalks'}:localDraft(context,category,title);}
  setDraft(result);setTitle(result.title);setCategory(result.category);setDescription(result.description);setObservations(result.observations);setResidentFacts(result.residentFacts);
 }catch(e){setError((e as Error).name==='TimeoutError'?'AI assistance timed out. Retry or finish your report manually.':`${(e as Error).message} You can still edit and submit manually.`);}finally{setBusy(false);}};
 const manualPin=()=>{const a=Number(lat),b=Number(lng);if(!lat.trim()||!lng.trim()||!Number.isFinite(a)||!Number.isFinite(b)||Math.abs(a)>90||Math.abs(b)>180){setError('Enter a valid latitude (-90 to 90) and longitude (-180 to 180).');return;}setError('');updatePin([a,b]);};
 const locate=()=>{if(!navigator.geolocation){setError('Device location is unavailable. Place a pin manually.');return;}setLocating(true);navigator.geolocation.getCurrentPosition(p=>{updatePin([p.coords.latitude,p.coords.longitude]);setLocating(false);setError('');},()=>{setError('Could not get device location. Select a point on the map or enter coordinates.');setLocating(false);},{timeout:10000,maximumAge:300000});};
 const submit=()=>{if(!photo||!pin||!confirmed){setError('Add a photo and confirm the map pin before submitting.');return;}if(!title.trim()||!description.trim()){setError('Add a short title and factual description. AI assistance is optional.');return;}const at=new Date().toISOString();onSubmit({id:`SF-${crypto.randomUUID().slice(0,8).toUpperCase()}`,title:title.trim(),description:description.trim(),category,lat:pin[0],lng:pin[1],location:location.trim()||`Pin ${pin[0].toFixed(5)}, ${pin[1].toFixed(5)}`,photos:[{id:crypto.randomUUID(),src:photo,alt:title.trim(),kind:'before',provenance:sample?'Representative licensed sample photo':'Resident-uploaded photo'}],submittedAt:at,residentContext:residentFacts.trim()||context.trim(),observations:observations.trim(),review:'awaiting',status:'Reported',priority:'Normal',priorityReason:'Awaiting staff assessment.',team:'Unassigned',targetDate:'',accessConcern:access.trim(),timeline:[{id:crypto.randomUUID(),at,actor:'Resident',text:'Photo, confirmed location, and reviewed report submitted.',status:'Reported'}]});};
 return <div className="report-flow"><ol className="flow-steps">{['Photo','Place & context','Review & submit'].map((name,i)=><li key={name} className={step===i+1?'current':step>i+1?'done':''}><span>{step>i+1?<Check size={13}/>:i+1}</span>{name}</li>)}</ol>
  {step===1&&<><PhotoPicker src={photo} onPhoto={changePhoto} onRemove={()=>changePhoto('')}/><div className="sample-option"><span>Need a photo for the interview demo?</span><button type="button" onClick={useSample}><Camera size={16}/> Use a labeled sample photo</button></div>{sample&&<p className="info-note">Representative licensed photo · fictional report fixture.</p>}<div className="flow-footer"><span>Your photo stays in this browser unless you explicitly use Live AI.</span><button className="primary" disabled={!photo} onClick={()=>{setError('');setStep(2);}}>Choose location</button></div></>}
  {step===2&&<><p className="field-help">Select the problem’s location on the map, then confirm the pin. A photo does not establish a location.</p><StreetMap reports={[]} pin={pin} onPin={updatePin} compact/><div className="coordinate-fields"><label>Latitude<input type="number" step="any" value={lat} onChange={e=>{setLat(e.target.value);setPin(null);setConfirmed(false);}}/></label><label>Longitude<input type="number" step="any" value={lng} onChange={e=>{setLng(e.target.value);setPin(null);setConfirmed(false);}}/></label><button className="secondary" onClick={manualPin}>Place pin</button></div><div className="pin-actions"><button className={confirmed?'confirmed-pin':'secondary'} disabled={!pin} onClick={()=>{setConfirmed(true);setError('');}}><Check size={16}/>{confirmed?'Location confirmed':'Confirm this location'}</button><button className="text-button" onClick={locate} disabled={locating}><LocateFixedIcon/>{locating?'Locating…':'Use device location'}</button></div><label className="field">Location / nearby landmark<input value={location} onChange={e=>setLocation(e.target.value)} placeholder="e.g. SE Salmon St, beside the crossing" maxLength={160}/></label><label className="field">What did you notice?<textarea value={context} onChange={e=>setContext(e.target.value)} placeholder="Describe what you saw and when you noticed it." maxLength={2000}/></label><label className="field">Access concern <span className="optional">(optional · resident-reported)</span><input value={access} onChange={e=>setAccess(e.target.value)} placeholder="e.g. I could not use the curb ramp" maxLength={300}/></label><div className="flow-footer"><button className="secondary" onClick={()=>setStep(1)}>Back</button><button className="primary" disabled={!confirmed} onClick={()=>{setError('');setDescription(description||context);setResidentFacts(residentFacts||context);setStep(3);}}>Review report</button></div></>}
  {step===3&&<><div className="ai-box"><div className="ai-heading"><Sparkles size={19}/><strong>Help with the words.</strong><Choose label="AI mode" disabled={busy} value={mode} options={[{value:'sample',label:'Sample AI draft'},{value:'live',label:'Live AI · Google Gemini'}]} onChange={v=>{setMode(v);setDraft(null);setError('');}}/></div><p>{mode==='live'?'Sends your photo and resident context to Google Gemini only when you request a draft. Staff decide priority and assignment.':sample?'Curated example for this known sample photo. This is not a live model analysis.':'Text-only help for your upload. The photo is not analyzed and no image observations will be invented.'}</p>{mode==='live'&&<label className="check-label"><Checkbox checked={consent} onCheckedChange={v=>setConsent(v===true)}/> I agree to send this photo and text to Google Gemini for this draft.</label>}<button className="secondary" disabled={busy} onClick={()=>void help()}>{busy?<LoaderCircle className="spin" size={16}/>:<Sparkles size={16}/>} {busy?'Preparing an editable draft…':error?'Retry: Help describe this issue':'Help describe this issue'}</button></div>
   {draft&&<div className="draft-note"><ShieldCheck size={17}/><div><strong>{mode==='live'?'Live AI draft · check every field':sample?'Sample AI draft · curated example':'Text-only draft · photo not analyzed'}</strong><span>Suggested routing: {draft.suggestedTeam}. City staff confirm the assignment.</span></div></div>}
   <label className="field">Short title<input value={title} onChange={e=>setTitle(e.target.value)} maxLength={100} placeholder="e.g. Pothole beside the bus stop"/></label><label className="field">Category<Choose label="Draft category" value={category} options={categories} onChange={v=>setCategory(v as Category)}/></label><label className="field">Factual description<textarea value={description} onChange={e=>setDescription(e.target.value)} maxLength={2000} placeholder="Describe the problem for the public works team."/></label><label className="field">Visible observations <span className="optional">(editable · optional)</span><textarea value={observations} onChange={e=>setObservations(e.target.value)} maxLength={2000} placeholder="Add what you can see. No image analysis is required."/></label><label className="field">Resident-reported facts<textarea value={residentFacts} onChange={e=>setResidentFacts(e.target.value)} maxLength={2000} placeholder="Your own context, separate from photo observations."/></label>{draft&&<div className="follow-up"><strong>Anything else you can tell us?</strong><ul>{draft.questions.map(q=><li key={q}>{q}</li>)}</ul><p>Add answers to resident-reported facts if you know them.</p></div>}<p className="submission-note"><MapPin size={15}/> Confirmed: {location||`${pin?.[0].toFixed(5)}, ${pin?.[1].toFixed(5)}`} · submitted as Awaiting review</p><div className="flow-footer"><button className="secondary" disabled={busy} onClick={()=>setStep(2)}>Back</button><button className="primary" disabled={busy} onClick={submit}>Submit report</button></div></>}
  {error&&<p className="form-error" role="alert">{error}</p>}
 </div>;
}
function LocateFixedIcon(){return <MapPin size={15}/>;}

function StaffForm({report:r,reports,onSave}:{report:Report;reports:Report[];onSave:(p:StaffPatch)=>boolean}){
 const [patch,setPatch]=useState<StaffPatch>({title:r.title,description:r.description,category:r.category,priority:r.priority,priorityReason:r.priorityReason,team:r.team,targetDate:r.targetDate,status:r.status,note:'',reviewAction:r.review==='awaiting'?'confirm':'keep',canonicalId:''});
 const [after,setAfter]=useState('');const field=<K extends keyof StaffPatch>(key:K,value:StaffPatch[K])=>setPatch(p=>({...p,[key]:value}));
 return <section className="staff-editor detail-section"><div className="staff-editor-heading"><Building2 size={18}/><h3>City staff workspace</h3></div><p className="field-help">Review the report and publish a clear next step. Updates are visible to residents immediately.</p>
  <label className="field">Review decision<Choose label="Review decision" value={patch.reviewAction} options={[{value:'keep',label:r.review==='awaiting'?'Keep awaiting review':'Already confirmed'},{value:'confirm',label:'Confirm report'},{value:'duplicate',label:'Mark as duplicate'}]} onChange={v=>field('reviewAction',v as StaffPatch['reviewAction'])}/></label>
  {patch.reviewAction==='duplicate'?<><label className="field">Canonical report<Choose label="Canonical report" value={patch.canonicalId||''} options={[{value:'',label:'Choose existing report'},...reports.filter(v=>v.id!==r.id&&v.review!=='duplicate').map(v=>({value:v.id,label:`${v.id} · ${v.title}`}))]} onChange={v=>field('canonicalId',v)}/></label><p className="info-note">This report and its history remain accessible. Supports stay on their original reports and will not be added together.</p></>:<>
  <label className="field">Report title<input value={patch.title} onChange={e=>field('title',e.target.value)} maxLength={100}/></label><label className="field">Report category<Choose label="Staff category" value={patch.category} options={categories} onChange={v=>field('category',v as Category)}/></label><label className="field">Report description<textarea value={patch.description} onChange={e=>field('description',e.target.value)} maxLength={2000}/></label><div className="two-fields"><label className="field">Staff priority<Choose label="Staff priority" value={patch.priority} options={priorities} onChange={v=>field('priority',v as StaffPatch['priority'])}/></label><label className="field">Assign team<Choose label="Assigned team" value={patch.team} options={teams} onChange={v=>field('team',v as StaffPatch['team'])}/></label></div><label className="field">Priority reason<input value={patch.priorityReason} onChange={e=>field('priorityReason',e.target.value)} maxLength={400}/></label><div className="two-fields"><label className="field">Repair status<Choose label="Repair status" value={patch.status} options={statuses.filter((_,i)=>i===statuses.indexOf(r.status)||i===statuses.indexOf(r.status)+1)} onChange={v=>field('status',v as StaffPatch['status'])}/></label><label className="field">Target date <span className="optional">(optional)</span><input type="date" value={patch.targetDate} onChange={e=>field('targetDate',e.target.value)}/></label></div><label className="field">Public {patch.status==='Fixed'?'completion update':'progress note'}<textarea value={patch.note} onChange={e=>field('note',e.target.value)} maxLength={1500} placeholder="What is happening, and what should residents know?"/></label>
  {patch.status==='Fixed'&&<><h4>Completion photo <span className="optional">(optional)</span></h4><PhotoPicker label="Completion photo" src={after} onPhoto={setAfter} onRemove={()=>setAfter('')}/></>}
  </>}
  <button className="primary full-width" onClick={()=>onSave({...patch,completionPhoto:after?{id:crypto.randomUUID(),src:after,alt:`Completed repair: ${patch.title}`,kind:'after'}:undefined})}><Check size={17}/> Save public update</button>
 </section>;
}
